# Generated by Django 3.2.9 on 2021-12-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.habit', unique_for_date='date'),
        ),
    ]
