# Generated by Django 3.2.9 on 2021-12-03 12:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailyrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
