# Generated by Django 3.2.9 on 2021-12-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('date', 'habit_id'), name='unique_daily_record'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('name', 'user_id'), name='unique_habit'),
        ),
    ]
