# Generated by Django 3.2.9 on 2021-12-06 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_dailyrecord_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
