# Generated by Django 3.2.9 on 2021-12-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_dailyrecord_quantity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyrecord',
            name='unique_daily_record',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='habit_id',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='tracker.habit', unique_for_date='date'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('date', 'habit'), name='unique_daily_record'),
        ),
    ]
