# Generated by Django 3.2.9 on 2021-12-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20211206_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='tracker.habit', unique_for_date='date'),
        ),
    ]
