# Generated by Django 3.2.9 on 2021-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_dailyrecord_habit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='unique_habit',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_habit'),
        ),
    ]
