# Generated by Django 3.2.9 on 2021-12-06 17:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20211206_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 12, 6))]),
        ),
    ]
