# Generated by Django 4.0 on 2021-12-07 22:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 12, 7))]),
        ),
    ]
