# Generated by Django 4.0 on 2021-12-08 04:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_dailyrecord_options_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 12, 8))]),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.habit', unique_for_date='date'),
        ),
    ]
