# Generated by Django 4.0 on 2021-12-14 13:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2021, 12, 14))]),
        ),
    ]
